### ISSUE TITLE
Disable/ enable  footer buttons until creation flow is not 'ready' for Marker Page

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio#45]
We should have some logic to enable footer buttons, so they can be clickable only if users has done all of the required actions (uploading content, choosing anchor - location or marker).

**Comment by thauska** [comment]
I've much time now and am studying this part.

**Comment by nicolocarpignoli** [comment]
@thauska how is this going? :)

**Comment by gciandro13** [comment]
Hi @thauska , still working on that? 
Otherwise I take a look on it ;)

**Comment by thauska** [comment]
I haven't look because I  was sick. @gciandro13 please see it.

**Comment by gciandro13** [comment]
Ok no problem for me! 
Everything is ok now? Hope you get well @thauska

**Comment by thauska** [comment]
I'm getting better. Just resting a little more to be able to help again.

**Comment by nicolocarpignoli** [comment]
Hi there. I disabled the footer buttons at startup.

On this issue we should enable them.
There are some window properties that tells you if content has been uploaded and markers/location have been chosen.

You should check them, and if both are true, you should enable the footer buttons (technically, they're a button and an 'a' element).

How to enable them:

- remove the 'publish-disabled' class on both
- set the 'href' to the 'a' element to the relative path of the 'publish.html' page

It should be okay. 

Final results:

- on both page ,if marker/location are set and content is set, footer buttons are both working and enabled
- otherwise, they're not clickable and with opacity.

**Comment by gciandro13** [comment]
@nicolocarpignoli  

Nic, a thought about that; in your opinion, what is the best moment to call the function that check if user uploaded both contents? 

I ask this because I think  it's not enough checking when user upload one of the two content; try thinking  if he decides to remove one of them... we have to react and be able to disable the footer as soon as he removes one of the two.

We can think of a "timeout checking", so the function is called every ms period, but I think that it is very expensive, maybe.. 

The other flow I see, is like this; calling the function "checkFooter" :
1. When user load a content, (enabling it)
2. When he removes a content, (disabling it)

In this second scenery, we have to think how to factorize the call of this checking function in case we upload audio, or image, or video... because it is better have a single calling point, but I do not know if it is simple factoring call-point according to the type-content chosen, and the code we have.

**Comment by nicolocarpignoli** [comment]
That's a good call. But, we are on the MVP phase so we can make things as simple as we can.

So the footer can be enabled only one time, that is: the first time both the contents are set.
So you can check, on marker.js, where window.marker... and the other global variable are set (so when marker is set, and when content is set) and in both places call a function that enables the footer.

**Comment by nicolocarpignoli** [comment]
We can just follow the KISS princiople for now :) 
https://en.wikipedia.org/wiki/KISS_principle

**Comment by gciandro13** [comment]
Pull request opened: https://github.com/AR-js-org/studio/pull/59
