### ISSUE TITLE
Improve Github deploy loading UI

### ISSUE THREAD

**Issue by nicolocarpignoli** [AR-js-org/studio#95]
We should enhance the loading page (final one) when Github is creating the page, because it may take up to several minutes, and so we should specify this better to the users.

**Comment by gciandro13** [comment]
I edit this issue because it is related to a "backend" bug:  we have got some reports about the fact that sometimes we have got sporadic error when we try to get github shareable link (error on screenshot).

![image](https://user-images.githubusercontent.com/20702863/94132102-196acf80-fe5f-11ea-8b34-0db117f4f4af.png)

**Comment by gciandro13** [comment]
Will be close in https://github.com/AR-js-org/studio/issues/108
